### ISSUE TITLE
cacert not Chef Client 13 Compatible

### ISSUE THREAD

**Issue by brownc** [chr4-cookbooks/cacert#4]
Hi Chris

As part of our upgrade prep for Chef Client 13, we're using sssd with cacert cookbooks.

When we run on Chef 12, we get the following against cacert:

```
Deprecated features used!
  Property `action` of resource `cacert` overwrites an existing method. Please use a different property name. This will raise an exception in Chef 13. at 1 location:
    - /var/chef/cache/cookbooks/cacert/resources/default.rb:29:in `class_from_file'
   See https://docs.chef.io/deprecations_property_name_collision.html for further details.
```

And indeed when we run Chef 13:

```
================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/cacert/resources/default.rb
================================================================================

ArgumentError
-------------
Property `action` of resource `cacert` overwrites an existing method.

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/cacert/resources/default.rb:29:in `class_from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/cacert/resources/default.rb:

 22:  default_action :create
 23:
 24:  attribute :cert,      kind_of: String, name_attribute: true
 25:  attribute :source,    kind_of: String, required: true
 26:  attribute :cert_dir,  kind_of: String, default: node['cacert']['cert_dir']
 27:  attribute :checksum,  kind_of: String, default: nil
 28:  attribute :cert_hash, kind_of: String, default: nil
 29>> attribute :action,    kind_of: Symbol, default: :create
 30:

System Info:
------------
chef_version=13.1.31
platform=amazon
platform_version=2017.03
ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
program_name=chef-client worker: ppid=22508;start=09:47:23;
executable=/opt/chef/bin/chef-client
```

Not sure I'm skilled enough to mess with that level of depth in your cookbook - is there any chance you could review/update for Chef 13 please?

Thanks for your help and cookbook contributions!

Chris B.

**Comment by chr4** [comment]
Thanks for the report!
I removed the line Chef-13 complains about and released the change in `v0.5.0`. 

Please reopen if the problem persists.

**Comment by brownc** [comment]
Hi Chris - this fix has worked a treat for me.  For the benefit of others, could you trigger via whatever mechanism you use, an upload into supermarket.chef.io when possible please?

Also just wanted to add - thanks for taking a look and resolving this so quickly, I really appreciate it!

**Comment by chr4** [comment]
Sorry, I've missed that! `v0.5.0` is now available in the supermarket.
